name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Auto-build and Resolve dependencies
      run: sudo apt update && ./build.sh

    - name: Packing into a tar and a deb
      run: ./pack.sh #&& cat /home/runner/work/OpenDX/OpenDX/build/_CPack_Packages/Linux/DEB/PreinstallOutput.log

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{env.BUILD_TYPE}}
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        path: |
          opendx.deb
          opendx.tar
        retention-days: 5
